import { User, Tournament, Team, Payment, LeaderboardEntry, Announcement, SpinReward } from './types';

export const initialUsers: User[] = [];
export const initialTournaments: Tournament[] = [];
export const initialTeams: Team[] = [];
export const initialPayments: Payment[] = [];
export const playerLeaderboard: LeaderboardEntry[] = [];
export const teamLeaderboard: LeaderboardEntry[] = [];
export const initialAnnouncements: Announcement[] = [];

export const spinRewards: SpinReward[] = [
  { id: '1', label: '100 Diamonds', type: 'DIAMONDS', value: 100, color: '#FF1E42' },
  { id: '2', label: '৳50 Wallet Cash', type: 'WALLET', value: 50, color: '#FF6B00' },
  { id: '3', label: 'Custom Room Card', type: 'ROOM_CARD', value: 1, color: '#00F0FF' },
  { id: '4', label: '25 Diamonds', type: 'DIAMONDS', value: 25, color: '#9D00FF' },
  { id: '5', label: '৳20 Wallet Cash', type: 'WALLET', value: 20, color: '#FFD700' },
  { id: '6', label: 'Try Again Tomorrow', type: 'TRY_AGAIN', value: 0, color: '#242436' },
];

export const initialBanners: import('./types').Banner[] = [
  {
    id: 'ban_main_1',
    title: 'GRAND FREE FIRE BR SQUAD LEAGUE #42',
    subtitle: '৳ 4,000 Cash Prize Pool • Instant bKash Payouts',
    badge: '🔥 LIVE CHAMPIONSHIP',
    imageUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1920&h=1080&fit=crop&q=85',
    linkUrl: '/tournaments',
    buttonText: 'JOIN TOURNAMENT',
    placement: 'MAIN_SLIDER',
    order: 1,
    isActive: true,
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'ban_main_2',
    title: 'CLASH SQUAD DAILY KNOCKOUT CUP',
    subtitle: 'Fast-paced 7 Rounds • High Kill Rewards & Trophies',
    badge: '⚡ 4v4 CS RANKED',
    imageUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1920&h=1080&fit=crop&q=85',
    linkUrl: '/arena',
    buttonText: 'ENTER ARENA',
    placement: 'MAIN_SLIDER',
    order: 2,
    isActive: true,
    createdAt: '2026-08-02T00:00:00Z',
  },
  {
    id: 'ban_main_3',
    title: 'INSTANT DIAMONDS & BATTLE PASS',
    subtitle: '100% In-Game Delivery within 2 Minutes via UID',
    badge: '💎 TOP-UP SPECIAL',
    imageUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1920&h=1080&fit=crop&q=85',
    linkUrl: '/shop',
    buttonText: 'TOP UP NOW',
    placement: 'MAIN_SLIDER',
    order: 3,
    isActive: true,
    createdAt: '2026-08-03T00:00:00Z',
  },
  {
    id: 'ban_side_top',
    title: 'CUSTOM ROOMS & DUEL ARENA',
    subtitle: 'Stake coins and win instant cash bonuses',
    badge: '👑 CUSTOM ROOMS',
    imageUrl: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=1920&h=1080&fit=crop&q=85',
    linkUrl: '/arena',
    buttonText: 'CUSTOM ROOMS',
    placement: 'SIDE_TOP',
    order: 1,
    isActive: true,
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'ban_side_bottom',
    title: 'LUCKY WHEEL & REWARDS',
    subtitle: 'Daily spins, promo coins & free pass entries',
    badge: '🎁 FREE REWARDS',
    imageUrl: 'https://images.unsplash.com/photo-1579373903781-fd5c0c30c4cd?w=1920&h=1080&fit=crop&q=85',
    linkUrl: '/ads',
    buttonText: 'SPIN NOW',
    placement: 'SIDE_BOTTOM',
    order: 1,
    isActive: true,
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'ban_shop_main',
    title: 'Gaming Shop & Diamond Center',
    subtitle: 'আপনার অর্জিত EZBD Coins (🪙) অথবা Wallet Taka (৳) দিয়ে ইনস্ট্যান্ট ফ্রি ফায়ার ডায়মন্ড, উইকলি মেম্বারশিপ, স্কিন রিডিম ভাউচার ও ম্যাচ পাস কিনুন!',
    badge: 'ESPORTS ZONE BD OFFICIAL REWARDS & COIN SHOP',
    imageUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1920&h=1080&fit=crop&q=85',
    linkUrl: '/shop',
    buttonText: 'VISIT GAMING SHOP',
    placement: 'SHOP_BANNER',
    order: 1,
    isActive: true,
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'ban_shop_diamonds',
    title: 'Instant UID Free Fire Diamond Top-Up',
    subtitle: '১০০% বিশ্বস্ত এবং দ্রুততম ফ্রি ফায়ার ডায়মন্ড ও উইকলি পাস রিডিম সার্ভিস — মাত্র ৫ মিনিটে ডেলিভারি!',
    badge: '⚡ INSTANT TOP-UP',
    imageUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1920&h=1080&fit=crop&q=85',
    linkUrl: '/shop',
    buttonText: 'TOP UP NOW',
    placement: 'SHOP_BANNER',
    order: 2,
    isActive: true,
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'ban_shop_membership',
    title: 'Weekly & Monthly Passes & Exclusive Bundles',
    subtitle: 'কয়েন এক্সচেঞ্জ ও ওয়ালেট ক্যাশ দিয়ে এক্সক্লুসিভ গেম বান্ডেল ও সিজন পাস সংগ্রহ করুন ডিসকাউন্ট মূল্যে!',
    badge: '👑 EXCLUSIVE DISCOUNTS',
    imageUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1920&h=1080&fit=crop&q=85',
    linkUrl: '/shop',
    buttonText: 'GET PASSES',
    placement: 'SHOP_BANNER',
    order: 3,
    isActive: true,
    createdAt: '2026-08-01T00:00:00Z',
  },
];
