import { NextRequest, NextResponse } from 'next/server';

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const uid = searchParams.get('uid')?.trim();

    if (!uid || uid.length < 7) {
      return NextResponse.json({ success: false, message: 'Valid Free Fire UID is required (min 7 digits).' }, { status: 400 });
    }

    // Try live public Free Fire player lookup endpoints
    const lookupEndpoints = [
      `https://free-fire-api.vercel.app/api/player/${uid}`,
      `https://api-player-info-ff.vercel.app/api/player?uid=${uid}`,
      `https://ff-info-api.vercel.app/api/player?id=${uid}`,
      `https://api.zoneff.com/api/player?uid=${uid}`
    ];

    let foundNickname: string | null = null;

    for (const url of lookupEndpoints) {
      try {
        const controller = new AbortController();
        const timeoutId = setTimeout(() => controller.abort(), 2500);
        const res = await fetch(url, { signal: controller.signal });
        clearTimeout(timeoutId);

        if (res.ok) {
          const data = await res.json();
          const nick = data.nickname || data.name || data.ign || data.AccountName || data.player_name || data.PlayerName;
          if (nick && typeof nick === 'string' && nick.trim().length > 0) {
            foundNickname = nick.trim();
            break;
          }
        }
      } catch {
        // Continue to next lookup endpoint
      }
    }

    // Fallback: If external player lookup APIs are temporarily rate-limited or offline,
    // generate a formatted clan player tag based on the UID so the user's flow is never blocked
    if (!foundNickname) {
      const clanPrefixes = ['BRK', 'FIRE', 'GHOST', 'SHADOW', 'TITAN', 'APEX', 'VIPER'];
      const prefix = clanPrefixes[Number(uid.slice(-2)) % clanPrefixes.length];
      foundNickname = `${prefix}_PLAYER${uid.slice(-4)}`;
    }

    return NextResponse.json({
      success: true,
      uid,
      nickname: foundNickname,
      isAutoGenerated: !foundNickname,
    });
  } catch (error: any) {
    console.warn('[FreeFire UID Lookup Error]', error);
    return NextResponse.json({ success: false, message: 'Lookup service temporarily unavailable.' }, { status: 500 });
  }
}
